# Generated by Django 5.2.8 on 2025-11-13 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('parties', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('negotiation_type', models.CharField(choices=[('SALE', 'Venda'), ('PURCHASE', 'Compra'), ('CONSIGNMENT', 'Consignação')], default='SALE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho / Em Aberto'), ('APPROVED', 'Aprovada / Fechada'), ('CANCELED', 'Cancelada')], default='DRAFT', max_length=20)),
                ('negotiation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Fechamento')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Final')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.entity', verbose_name='Cliente/Fornecedor')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Negociação',
                'verbose_name_plural': 'Negociações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agreed_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Acordado')),
                ('flow', models.CharField(choices=[('OUT', 'Saída (Venda do Estoque)'), ('IN', 'Entrada (Troca/Compra)')], max_length=10, verbose_name='Fluxo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negotiations.negotiation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Item da Negociação',
                'verbose_name_plural': 'Itens da Negociação',
                'unique_together': {('negotiation', 'vehicle')},
            },
        ),
    ]
