# Generated by Django 5.2.8 on 2025-11-13 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicles.brand', verbose_name='Marca')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('chassi', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Chassi')),
                ('plate', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, max_length=20, null=True, verbose_name='Renavam')),
                ('year_fab', models.PositiveIntegerField(verbose_name='Ano Fab.')),
                ('year_model', models.PositiveIntegerField(verbose_name='Ano Mod.')),
                ('color', models.CharField(max_length=30, verbose_name='Cor')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Quilometragem (KM)')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('ETHANOL', 'Etanol'), ('FLEX', 'Flex'), ('DIESEL', 'Diesel'), ('HYBRID', 'Híbrido'), ('ELECTRIC', 'Elétrico')], default='FLEX', max_length=20, verbose_name='Combustível')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('MAINTENANCE', 'Em Manutenção'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], db_index=True, default='AVAILABLE', max_length=20)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo de Aquisição')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_proprietario', to='parties.entity', verbose_name='Proprietário Atual')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.model', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'indexes': [models.Index(fields=['status', 'model'], name='vehicles_ve_status_81996a_idx')],
            },
        ),
    ]
