# Generated by Django 5.2.8 on 2025-11-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('MAINTENANCE', 'Em Manutenção'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido'), ('WRITE_OFF', 'Baixado / Perda Total')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
