# Generated by Django 5.2.8 on 2025-11-13 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('APPROVED', 'Aprovada / Em Execução'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='REQUESTED', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_provided', to='parties.entity', verbose_name='Fornecedor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço (OS)',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Serviço/Peça')),
                ('category', models.CharField(choices=[('MECHANIC', 'Mecânica'), ('BODYWORK', 'Funilaria/Pintura'), ('AESTHETICS', 'Estética/Lavagem'), ('PARTS', 'Peças'), ('DOCUMENTATION', 'Documentação/Despachante'), ('OTHER', 'Outros')], default='MECHANIC', max_length=20, verbose_name='Categoria')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.serviceorder')),
            ],
            options={
                'verbose_name': 'Item da OS',
                'verbose_name_plural': 'Itens da OS',
            },
        ),
    ]
