# Generated by Django 5.2.8 on 2025-11-13 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código Contábil')),
                ('operation_type', models.CharField(choices=[('REVENUE', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='financial.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Planos de Contas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('account_type', models.CharField(choices=[('CASH', 'Caixa Físico'), ('BANK', 'Conta Bancária')], default='BANK', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Atual')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('transaction_type', models.CharField(choices=[('PAYABLE', 'A Pagar'), ('RECEIVABLE', 'A Receber')], max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('OPEN', 'Em Aberto'), ('PARTIAL', 'Pago Parcialmente'), ('PAID', 'Quitado'), ('CANCELED', 'Cancelado')], db_index=True, default='OPEN', max_length=15)),
                ('due_date', models.DateField(db_index=True, verbose_name='Data de Competência/Vencimento')),
                ('description', models.TextField(verbose_name='Histórico/Descrição')),
                ('chart_of_accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.chartofaccounts', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.entity', verbose_name='Entidade (Parceiro)')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='vehicles.vehicle', verbose_name='Veículo (Centro de Custo)')),
            ],
            options={
                'verbose_name': 'Lançamento (Ledger)',
                'verbose_name_plural': 'Lançamentos',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Nº Parcela')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Parcela')),
                ('paid_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Pago')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('TRANSFER', 'TED/PIX'), ('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão Crédito'), ('FINANCING', 'Financiamento')], max_length=20, null=True, verbose_name='Forma Pagto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('financial_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.financialaccount', verbose_name='Conta Movimentada')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financial.ledger')),
            ],
            options={
                'verbose_name': 'Parcela / Movimentação',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['status', 'due_date'], name='financial_l_status_6ca35c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['transaction_type'], name='financial_l_transac_4a9124_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('ledger', 'installment_number')},
        ),
    ]
