# Generated by Django 5.2.8 on 2025-11-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='negotiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negotiations.negotiation', verbose_name='Origem da Negociação'),
        ),
    ]
