# Generated by Django 5.2.8 on 2025-11-13 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja_id', models.IntegerField(default=1, verbose_name='ID da Loja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cargo', models.CharField(max_length=100)),
                ('comissao_base_percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Comissão Base (%)')),
                ('ativo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('entidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='colaborador_profile', to='parties.entity', verbose_name='Dados Pessoais (Entidade)')),
                ('usuario_sistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
